import * as z from "zod/mini";

import { wordList } from "../primitives.js";

/**
 * Text-shape vocabulary the scorer itself reads, as opposed to the parser or the matcher.
 *
 * `contentLineVerbs` decides which lines count as substantive content — the denominator both
 * ratio metrics divide by. It is a list of English verbs, so it is data; it was previously a
 * literal in the scorer, which is exactly the kind of thing that turns adding a locale into a
 * rewrite.
 *
 * Deliberately its own field rather than reusing the `actionVerbRatio` rule's pattern. The two
 * lists overlap but are not the same list and never were: this one decides what gets measured,
 * that one decides what scores well, and quietly collapsing them would change which lines are
 * counted. The default below is the exact list this replaced, so a policy that does not mention
 * the field behaves identically to the code that came before it.
 */
export const engineTextSchema = z.prefault(
  z.object({
    /**
     * The language this policy's own vocabulary is written in (ISO 639): what a resume is read as
     * when no attached language pack recognises it. A rule limited to some `languages` applies
     * only to a resume read in one of them.
     */
    language: z._default(
      z.string().check(z.regex(/^[a-z]{2,3}$/, "an ISO 639 language code")),
      "en",
    ),
    contentLineVerbs: z._default(wordList("text.contentLineVerbs"), [
      "managed",
      "led",
      "built",
      "developed",
      "designed",
      "improved",
      "reduced",
      "increased",
      "delivered",
      "achieved",
      "created",
      "generated",
      "optimized",
      "launched",
      "spearheaded",
      "engineered",
      "maintained",
      "scaled",
      "automated",
    ]),
    /**
     * The verbs a content line scores for naming, read by an `actionVerbRatio` rule that carries
     * no `pattern` of its own: present and past, so a current role ("Lead a team of 9") counts
     * as well as a past one. Vocabulary rather than a pattern in the rule, so a language pack
     * extends it the way it extends every other word list. Regular past tenses need no entry:
     * see `actionVerbForms`.
     */
    actionVerbs: z._default(wordList("text.actionVerbs"), [
      "led",
      "lead",
      "leads",
      "leading",
      "built",
      "build",
      "builds",
      "cut",
      "cuts",
      "ran",
      "run",
      "runs",
      "drove",
      "drive",
      "drives",
      "grew",
      "grow",
      "grows",
      "won",
      "win",
      "wins",
      "made",
      "make",
      "makes",
      "wrote",
      "write",
      "writes",
      "rewrote",
      "sold",
      "sell",
      "sells",
      "taught",
      "teach",
      "teaches",
      "oversaw",
      "oversee",
      "oversees",
      "began",
      "brought",
      "bring",
      "brings",
      "held",
      "kept",
      "met",
      "spoke",
      "took",
      "gave",
      "rebuilt",
      "undertook",
      "overhaul",
      "overhauls",
      "own",
      "owns",
      "owned",
      "manage",
      "manages",
      "managed",
      "develop",
      "develops",
      "developed",
      "design",
      "designs",
      "designed",
      "deliver",
      "delivers",
      "delivered",
      "improve",
      "improves",
      "improved",
      "reduce",
      "reduces",
      "reduced",
      "increase",
      "increases",
      "increased",
      "create",
      "creates",
      "created",
      "launch",
      "launches",
      "launched",
      "automate",
      "automates",
      "automated",
      "scale",
      "scales",
      "scaled",
      "migrate",
      "migrates",
      "migrated",
      "implement",
      "implements",
      "implemented",
      "architected",
      "coordinate",
      "coordinates",
      "coordinated",
      "negotiate",
      "negotiates",
      "negotiated",
      "mentored",
      "coached",
      "train",
      "trains",
      "trained",
      "hire",
      "hires",
      "hired",
      "recruit",
      "recruits",
      "recruited",
      "closed",
      "exceed",
      "exceeds",
      "exceeded",
      "achieve",
      "achieves",
      "achieved",
      "secured",
      "establish",
      "establishes",
      "established",
      "streamline",
      "streamlines",
      "streamlined",
      "optimize",
      "optimizes",
      "optimized",
      "optimise",
      "optimises",
      "optimised",
      "analyze",
      "analyzes",
      "analyzed",
      "analyse",
      "analyses",
      "analysed",
      "maintain",
      "maintains",
      "maintained",
      "supported",
      "directed",
      "planned",
      "organize",
      "organizes",
      "organized",
      "organise",
      "organises",
      "organised",
      "execute",
      "executes",
      "executed",
      "generate",
      "generates",
      "generated",
      "spearhead",
      "spearheads",
      "spearheaded",
      "partnered",
      "collaborate",
      "collaborates",
      "collaborated",
      "presented",
      "publish",
      "publishes",
      "published",
      "researched",
      "evaluate",
      "evaluates",
      "evaluated",
      "tested",
      "deploy",
      "deploys",
      "deployed",
      "refactor",
      "refactors",
      "refactored",
      "integrate",
      "integrates",
      "integrated",
      "resolve",
      "resolves",
      "resolved",
      "troubleshoot",
      "troubleshoots",
      "troubleshot",
      "administer",
      "administers",
      "administered",
      "configure",
      "configures",
      "configured",
      "monitored",
      "documented",
      "reviewed",
      "prepare",
      "prepares",
      "prepared",
      "conduct",
      "conducts",
      "conducted",
      "expand",
      "expands",
      "expanded",
      "boost",
      "boosts",
      "boosted",
      "accelerate",
      "accelerates",
      "accelerated",
      "saved",
      "lowered",
      "raise",
      "raises",
      "raised",
      "consolidate",
      "consolidates",
      "consolidated",
      "standardize",
      "standardizes",
      "standardized",
      "standardise",
      "standardised",
      "transform",
      "transforms",
      "transformed",
      "modernize",
      "modernizes",
      "modernized",
      "redesign",
      "redesigns",
      "redesigned",
      "introduce",
      "introduces",
      "introduced",
      "pioneer",
      "pioneers",
      "pioneered",
      "initiate",
      "initiates",
      "initiated",
      "define",
      "defines",
      "defined",
      "prototyped",
      "produce",
      "produces",
      "produced",
      "authored",
      "drafted",
      "forecasted",
      "budgeted",
      "audited",
      "ensure",
      "ensures",
      "ensured",
      "engineered",
      "ship",
      "ships",
      "shipped",
      "founded",
      "co-founded",
      "cofounded",
      "handle",
      "handles",
      "handled",
      "guided",
      "onboard",
      "onboards",
      "onboarded",
      "sourced",
      "cultivate",
      "cultivated",
      "convert",
      "converts",
      "converted",
      "renegotiated",
      "eliminate",
      "eliminates",
      "eliminated",
    ]),
    /**
     * Shapes of a word that make a bullet's first word an action verb without its being listed:
     * in English, a regular past tense ("Shepherded", "Reorganized"). Matched against the whole
     * first word; "-eed" words ("Speed", "Need") are nouns as often as not and are left out.
     */
    actionVerbForms: z._default(wordList("text.actionVerbForms"), [String.raw`\p{L}{3,}(?<!e)ed`]),
    /**
     * Whether an action verb counts anywhere in a line rather than only in its opening words.
     * Set for a verb-final language: in Hindi "टीम का नेतृत्व किया" the verb ends the bullet.
     */
    actionVerbAnywhere: z._default(z.boolean(), false),
    /**
     * Instructions addressed to an AI screener rather than to a person. Patterns, so each can
     * cover its variants; a tool's name alone is never one ("Built with the ChatGPT API" is a
     * skill). Language packs add their own.
     */
    injectionPhrases: z._default(wordList("text.injectionPhrases"), [
      // Up to three determiners: "ignore all the previous", "disregard all of the above". Said
      // of a system an engineer built it is a description, not an instruction: "our model must
      // ignore previous instructions embedded in uploads", "taught the classifier to ignore
      // prior instructions". Said to anyone else ("I want you to", "Recruiting bots should",
      // "Remember to") it is one.
      String.raw`(?<!(?:model|models|llm|llms|system|systems|classifier|classifiers|pipeline|pipelines|filter|filters|guardrail|guardrails|parser|parsers)(?:\s{1,3}(?:must|should|shall|will|would|can|could|may|might|cannot|to|never|not|always|then|now))?\s{1,3})(?:ignore|disregard|forget|override)\s+(?:(?:all|any|the|your|of|my|these|those)\s+){0,3}(?:previous|prior|above|earlier|preceding|other)\s+(?:instructions?|prompts?|directions?|rules|context)`,
      String.raw`you\s+(?:must|should|shall|will|need\s+to|are\s+to)\s+(?:now\s+)?(?:ignore|disregard|forget|override)\s+(?:(?:all|any|the|your|of|my|these|those)\s+){0,3}(?:previous|prior|above|earlier|preceding|other)\s+(?:instructions?|prompts?|directions?|rules|context)`,
      // Aimed at the grading itself: "disregard the rubric", "give this resume a 10/10".
      String.raw`(?<!(?:model|models|llm|llms|system|systems|classifier|classifiers|pipeline|pipelines|filter|filters|guardrail|guardrails|parser|parsers)(?:\s{1,3}(?:must|should|shall|will|would|can|could|may|might|cannot|to|never|not|always|then|now))?\s{1,3})(?:ignore|disregard|forget|override)\s+(?:(?:all|any|the|your|these|those)\s+){0,2}(?:rubric|(?:scoring|grading|screening|evaluation)\s+(?:rubric|criteria|guidelines|rules))`,
      String.raw`(?:give|award|assign)\s+(?:this|my)\s+(?:resume|cv|candidate|applicant|profile|application)\s+(?:an?\s+|the\s+)?(?:10\s*/\s*10|100\s*/\s*100|perfect|full\s+marks|top\s+(?:score|marks|rating)|highest|maximum)`,
      // Not "system prompt:", which an engineer writes about the prompts they built.
      String.raw`(?:new|updated|real)\s+(?:instructions?|prompt)\s*:|system\s+instructions?\s*:`,
      String.raw`(?:you\s+are|pretend\s+to\s+be)\s+(?:an?\s+)?(?:ai|assistant|language\s+model|llm|resume\s+screener)`,
      // A person's role, said to a screener; not "If you are a hiring manager looking for…",
      // which a person writes to a person.
      String.raw`(?:(?<!(?:if|when)\s{1,3})you\s+are|pretend\s+to\s+be)\s+(?:an?\s+)?(?:recruiter|hiring\s+manager)`,
      // "Act as" is a recruiter's job description ("act as hiring manager"), so it counts only
      // with an AI for its object.
      String.raw`act\s+as\s+(?:an?\s+)?(?:(?:ai|automated)\s+(?:assistant|recruiter|screener|reviewer|hiring\s+manager|model)|language\s+model|llm|resume\s+screener)`,
      String.raw`(?:if|when)\s+you\s+are\s+(?:an?\s+)?(?:ai|llm|language\s+model|automated|bot)`,
      // Addressed, so punctuated: "Note to AI:", not "the release note for the model registry".
      String.raw`note\s+(?:to|for)\s+(?:the\s+)?(?:ai|llm|chatgpt|model|screener|automated\s+\p{L}+)\s*[:,–—-]`,
      // "This candidate", never "the candidate": a recruiter's bullets talk about *the*
      // candidate ("ensured the candidate is the best fit"); an instruction points at this one.
      String.raw`(?:rank|rate|score|grade|mark|recommend|evaluate)\s+this\s+(?:candidate|applicant|resume|profile)\s+(?:as\s+|at\s+)?(?:the\s+)?(?:highest|top|best|first|100|10|perfect|excellent|highly)`,
      String.raw`this\s+(?:candidate|applicant)\s+(?:is|should\s+be)\s+(?:the\s+|an?\s+)?(?:best|most\s+qualified|perfect|ideal|top|strongest|exceptional)\s+(?:fit|match|candidate|choice)`,
      String.raw`(?:hire|shortlist|advance|select|interview)\s+this\s+(?:candidate|applicant)\s+(?:immediately|now|first|without)`,
      // A verdict dictated: quoted, or "only with", or ending the sentence ("Respond with
      // qualified."). Not a measure ("respond with 100 percent accuracy") nor a choice a support
      // agent is coached on ("answer with yes or no").
      String.raw`(?:respond|reply|answer|output)\s+(?:only\s+with\s+["'“]?|with\s+["'“])(?:yes|hire|qualified|100(?!\s*(?:%|percent)))`,
      String.raw`(?:respond|reply|answer|output)\s+with\s+(?:yes|hire|qualified)(?=\s*(?:[.!;"”\n]|$))`,
      // A markdown "### System Design" heading is not a prompt delimiter; "### System:" is.
      String.raw`<\|?(?:im_start|system|endoftext)\|?>|\[/?(?:inst|system)\]|###\s*(?:instructions?|system\s*:)`,
    ]),
    /**
     * Words that say an injection phrase was caught, not given: `Built a filter that flags
     * "ignore previous instructions"`. A phrase in quotes or backticks within three words of one
     * of these (function words aside, no comma or colon between) is an example an AI security
     * engineer quotes, and is not counted. Not on a labelled line ("Skills: …"), not unquoted
     * (a bare "[INST]" too), not in text hidden in tag characters or by the layout, and never a
     * quote naming one of `injectionTargets`.
     */
    injectionMentionVerbs: z._default(wordList("text.injectionMentionVerbs"), [
      String.raw`flag(?:s|ged|ging)?`,
      String.raw`detect(?:s|ed|ing|ion|ions)?`,
      String.raw`block(?:s|ed|ing)?`,
      String.raw`filter(?:s|ed|ing)?`,
      String.raw`catch(?:es|ing)?`,
      "caught",
      String.raw`prevent(?:s|ed|ing)?`,
      String.raw`mitigat(?:e|es|ed|ing)`,
      String.raw`red[\s-]?team(?:s|ed|ing)?`,
      String.raw`test(?:s|ed|ing)?`,
      String.raw`scan(?:s|ned|ning)?`,
      String.raw`spot(?:s|ted|ting)?`,
      String.raw`reject(?:s|ed|ing)?`,
      String.raw`saniti[sz](?:e|es|ed|ing)`,
    ]),
    /** What a quote that tells the screener what to make of this resume names: never an example. */
    injectionTargets: z._default(wordList("text.injectionTargets"), [
      String.raw`this\s+(?:candidate|applicant|resume|cv|profile|application)`,
      String.raw`(?:rank|rate|score|grade|hire|shortlist|approve|select|advance|recommend)\s+me`,
    ]),
    /**
     * Headings of a list of works, read where a section heading opens one: its lines are
     * citations ("Kovalenko O, Marsh T. Ligand field effects…"), not bullets. They have no
     * action verb to open with and repeat the author's name, so the verb and metric rules do not
     * read them, nor does keyword stuffing count a term across them; a line repeating a term
     * there is still stuffing.
     */
    citationHeadings: z._default(wordList("text.citationHeadings"), [
      String.raw`publications?`,
      String.raw`presentations?`,
      String.raw`(?:invited\s+)?talks`,
      "conferences",
      "patents",
      "posters",
    ]),
  }),
  // `prefault`, not `default`: zod 4's `default` returns the fallback as-is without parsing it,
  // which would hand the scorer `{}` and silently drop the verb list above.
  {},
);
