import * as z from "zod/mini";

import { wordList } from "../primitives.js";

/**
 * What the writing rules read (`checks/writing.ts`): style a recruiter notices once the ATS has
 * read the resume — bullets in the first person or the passive voice, duties instead of actions,
 * a tense that does not fit the role. English vocabulary: the rules that read it carry
 * `languages: ["en"]` and are dropped for a resume read in any other language, so a language
 * pack has nothing to add here until it brings rules of its own.
 *
 * Every list is matched against whole words, case-insensitively; entries may be small patterns,
 * as in every other word list.
 */
export const writingSchema = z.prefault(
  z.object({
    /**
     * A bullet speaking in the first person. "I" is not read before a dot or slash and a letter:
     * "i.e." and "I/O" are not pronouns. "us" is left out for "US".
     */
    firstPersonPronouns: z._default(wordList("writing.firstPersonPronouns"), [
      String.raw`I(?![./&]\p{L})`,
      "me",
      "my",
      "mine",
      "myself",
      "we",
      "our",
      "ours",
      "ourselves",
    ]),
    /** An auxiliary that, followed by a participle, makes a clause passive. */
    passiveAuxiliaries: z._default(wordList("writing.passiveAuxiliaries"), [
      "was",
      "were",
      "been",
      "being",
      "is",
      "are",
    ]),
    /**
     * Shapes of a regular past tense or past participle, matched against a whole word: "-ed",
     * with at least two letters before it ("used", not "red") and not "-eed" ("need", "speed").
     */
    pastForms: z._default(wordList("writing.pastForms"), [String.raw`\p{L}{2,}(?<!e)ed`]),
    /** A word that may stand between the auxiliary and the participle: "was quickly adopted". */
    adverbForms: z._default(wordList("writing.adverbForms"), [String.raw`\p{L}{2,}ly`]),
    /** Past participles that do not end in "-ed": "was built", "were led". */
    irregularParticiples: z._default(wordList("writing.irregularParticiples"), [
      "built",
      "rebuilt",
      "led",
      "made",
      "written",
      "rewritten",
      "given",
      "taken",
      "undertaken",
      "chosen",
      "done",
      "seen",
      "overseen",
      "shown",
      "known",
      "grown",
      "driven",
      "held",
      "sold",
      "won",
      "brought",
      "taught",
      "bought",
      "found",
      "kept",
      "sent",
      "spent",
      "paid",
      "begun",
      "drawn",
      "thrown",
      "spoken",
      "broken",
      "hidden",
      "set",
      "put",
      "cut",
      "run",
    ]),
    /** Openings that state a duty rather than an action. Matched at the start of a bullet. */
    weakOpeners: z._default(wordList("writing.weakOpeners"), [
      String.raw`responsible\s+for`,
      String.raw`duties\s+included`,
      String.raw`duties\s+include`,
      String.raw`helped\s+with`,
      String.raw`worked\s+on`,
      String.raw`tasked\s+with`,
      String.raw`assisted\s+with`,
      String.raw`involved\s+in`,
      String.raw`in\s+charge\s+of`,
    ]),
    /**
     * Past tenses that do not end in "-ed", for a bullet's first word. Words that read as past
     * and present alike ("cut", "set", "read") are in neither list, so they are never judged.
     */
    pastTenseVerbs: z._default(wordList("writing.pastTenseVerbs"), [
      "led",
      "built",
      "rebuilt",
      "ran",
      "drove",
      "grew",
      "won",
      "made",
      "wrote",
      "rewrote",
      "sold",
      "began",
      "brought",
      "taught",
      "found",
      "kept",
      "held",
      "spent",
      "sent",
      "met",
      "oversaw",
      "became",
      "chose",
      "gave",
      "took",
      "undertook",
      "saw",
      "bought",
      "sought",
      "spoke",
      "drew",
      "overcame",
      "paid",
      "rose",
      "stood",
      "understood",
      "withdrew",
    ]),
    /**
     * Present tenses a bullet opens with: the base form and, where it is not as often a plural
     * noun ("reports", "tests"), the third person.
     */
    presentTenseVerbs: z._default(wordList("writing.presentTenseVerbs"), [
      "lead",
      "leads",
      "manage",
      "manages",
      "build",
      "builds",
      "develop",
      "develops",
      "design",
      "designs",
      "own",
      "owns",
      "run",
      "runs",
      "drive",
      "drives",
      "oversee",
      "oversees",
      "maintain",
      "maintains",
      "create",
      "creates",
      "implement",
      "implements",
      "coordinate",
      "coordinates",
      "deliver",
      "delivers",
      "write",
      "writes",
      "mentor",
      "analyze",
      "analyzes",
      "analyse",
      "direct",
      "directs",
      "handle",
      "handles",
      "collaborate",
      "collaborates",
      "grow",
      "grows",
      "improve",
      "improves",
      "reduce",
      "reduces",
      "increase",
      "increases",
      "launch",
      "ship",
      "scale",
      "automate",
      "automates",
      "define",
      "defines",
      "establish",
      "establishes",
      "negotiate",
      "negotiates",
      "sell",
      "sells",
      "recruit",
      "recruits",
      "prepare",
      "prepares",
      "conduct",
      "conducts",
      "monitor",
      "monitors",
      "optimize",
      "optimizes",
      "serve",
      "serves",
      "teach",
      "teaches",
      "provide",
      "provides",
      "ensure",
      "ensures",
      "spearhead",
      "spearheads",
      "facilitate",
      "facilitates",
      "resolve",
      "resolves",
      "administer",
      "administers",
      "deploy",
      "deploys",
      "migrate",
      "migrates",
      "support",
      "supports",
    ]),
    /** A bullet longer than this many words runs past about two printed lines. */
    maxBulletWords: z._default(z.number().check(z.int(), z.gt(0)), 40),
    /** A role with bullets should have this many; one with none is not counted. */
    bulletsPerRole: z._default(
      z
        .object({
          min: z.number().check(z.int(), z.gte(0)),
          max: z.number().check(z.int(), z.gt(0)),
        })
        .check(z.refine((range) => range.min <= range.max, { message: "min must not exceed max" })),
      { min: 2, max: 8 },
    ),
    /** This many bullets in a row opening with the same word is a run. */
    repeatedOpenerRun: z._default(z.number().check(z.int(), z.gte(2)), 3),
  }),
  // `prefault`, as `text`: a policy written before these existed still parses, with the defaults.
  {},
);
