/** The community policy's job-matching vocabulary and weights. */
export const DEFAULT_KEYWORD_MATCH = {
  // Round, obviously-illustrative numbers. They encode only the ordering the engine needs — a
  // stated requirement outranks the body, which outranks a nice-to-have, and ordinary English is
  // discounted against a recognised skill. The *tuned* values are calibration and stay private;
  // anything here that happened to match them would be shipping the moat in the demo.
  requiredWeight: 2,
  preferredWeight: 0.5,
  responsibilitiesWeight: 0.5,
  defaultWeight: 1,
  generalTermWeight: 0.25,
  // A soft skill weighs this much of an ordinary word: 0.1 of a recognised skill.
  softSkillWeight: 0.4,
  sections: {
    // "Minimum qualifications", "Basic Qualifications", "Must-haves", "What you bring", "About
    // you", "Skills and Qualifications", "What we're looking for": a posting whose required
    // heading went unread lost every required item, and its heading words became keywords.
    required: String.raw`^(?:(?:minimum|basic|required|essential|key|core)\s+)?(?:requirements|qualifications|skills)|^(?:what\s+you.{0,3}ll\s+need|what\s+you\s+(?:bring|need|have)|what\s+we(?:.{0,3}re|\s+are)\s+looking\s+for|must[\s-]+haves?|about\s+you|your\s+profile|who\s+you\s+are|you\s+have|you\s+bring)`,
    preferred: String.raw`^(?:nice[\s-]+to[\s-]+haves?|preferred|bonus|desirable|desired|plus)`,
    responsibilities: String.raw`^(?:responsibilities|what\s+you.{0,3}ll\s+do|the\s+role|about\s+the\s+role)`,
    // "About Acme Robotics" is the employer's own section; its name is never a keyword. "About
    // you" (required) and "About the role" (responsibilities) are matched before this.
    excluded: String.raw`^(?:about\s+us|benefits|perks|(?:what\s+)?we\s+offer|equal\s+opportunity|our\s+values|why\s+join|about\s+(?!(?:you|your|the|this)(?![\p{L}]))[\p{L}\p{N}&.'-]{1,40}(?:\s+[\p{L}\p{N}&.'-]{1,40}){0,3})`,
  },
  stopwords: [
    "the",
    "and",
    "for",
    "with",
    "you",
    "your",
    "our",
    "are",
    "will",
    "have",
    "this",
    "that",
    "from",
    "they",
    "them",
    "who",
    "was",
    "were",
    "been",
    "has",
    "had",
    "not",
    "but",
    "all",
    "can",
    "any",
    "may",
    "more",
    "most",
    "other",
    "some",
    "such",
    "than",
    "then",
    "there",
    "these",
    "those",
    "into",
    "over",
    "also",
    "about",
    "work",
    "working",
    "team",
    "teams",
    "role",
    "years",
    "year",
    "experience",
    "strong",
    "good",
    "great",
    "excellent",
    "ability",
    "skills",
    "knowledge",
    "understanding",
    "familiarity",
    "proficiency",
    "including",
    "etc",
    "new",
    "well",
    "help",
    "join",
    "looking",
    "candidate",
    "candidates",
    "opportunity",
    "company",
    "business",
    "across",
    "within",
    "using",
    "use",
    "like",
    "make",
    "need",
    "needs",
    "want",
    "plus",
    "must",
    // Function words. Terms of one or two letters are already dropped unless they are a
    // named skill, but the longer ones and the posting filler below still reached the report.
    "a",
    "an",
    "as",
    "at",
    "be",
    "by",
    "in",
    "is",
    "it",
    "its",
    "of",
    "on",
    "or",
    "to",
    "we",
    "us",
    "via",
    "per",
    "off",
    // Kept whole, a slash and all: "N/A" is no skill "N".
    "n/a",
    "deep",
    "hands",
    "hands-on",
    "prior",
    "exposure",
    "solid",
    "proven",
    "demonstrated",
    "preferred",
    "required",
    "ideally",
    // Words that open a capitalised sentence and would otherwise read as a two-letter acronym.
    "i",
    "no",
    "so",
    "do",
    "if",
    "up",
    "me",
    "my",
    "he",
    // "his/her" splits into its words.
    "his",
    "her",
    "him",
    "she",
    // Posting filler: where and how the job is, and words around a requirement rather than in it.
    "hiring",
    "hire",
    "hybrid",
    "remote",
    "onsite",
    "on-site",
    "track",
    "record",
    "million",
    "billion",
    "related",
    "relevant",
    "field",
    "professional",
    "environment",
    "fast-paced",
    "industry",
    "similar",
    "equivalent",
    "another",
    "least",
    // How many years, not of what: "Minimum of 5 years", "Min. 5 years".
    "minimum",
    "min",
    "age",
    "old",
    "older",
    "degree",
    "degrees",
    "position",
    "ideal",
    "successful",
    "responsible",
    // How well a language is spoken; the language is the requirement.
    "fluent",
    "fluency",
    // How a soft skill is used: "written and verbal communication" asks for communication.
    "written",
    "verbal",
  ],
  synonyms: {
    js: "javascript",
    ts: "typescript",
    k8s: "kubernetes",
    postgres: "postgresql",
    psql: "postgresql",
    golang: "go",
    py: "python",
    iac: "infrastructure as code",
    // "CI" alone is continuous integration; "CD" alone is as often a compact disc.
    ci: "ci/cd",
    nodejs: "node.js",
    node: "node.js",
    reactjs: "react",
    "react.js": "react",
    // A soft skill's other spellings, so "communicating" in a posting meets "communication" on a
    // resume. Each is a soft skill, never a hard one (see `softSkills`).
    communicate: "communication",
    communicates: "communication",
    communicated: "communication",
    communicating: "communication",
    communicator: "communication",
    communicative: "communication",
    collaborate: "collaboration",
    collaborates: "collaboration",
    collaborated: "collaboration",
    collaborating: "collaboration",
    collaborative: "collaboration",
    collaboratively: "collaboration",
    adaptable: "adaptability",
    empathetic: "empathy",
    "multi-tasking": "multitasking",
    "problem-solving": "problem solving",
    "decision-making": "decision making",
    "detail-oriented": "attention to detail",
    "self-motivated": "self motivated",
    "critical-thinking": "critical thinking",
    "team-player": "team player",
  },
  // What a posting asks of the person rather than of their work. They weigh `softSkillWeight` of
  // an ordinary word and the report lists them apart. Placed by one test: does a resume evidence
  // it with an outcome, or only claim it? Borderline terms stay hard skills:
  // - "mentoring" and "coaching": a duty with an object a resume shows ("Mentored four
  //   engineers"); the requirements judge already holds a mentoring ask to a line that shows it.
  // - "project management": a discipline with methods, tools and certifications (PMP, PRINCE2).
  // - "negotiation": in the roles that name it (sales, procurement) the job itself, measured in
  //   deals and terms; a soft discount would hide a sales resume's real gap.
  // - "customer service", "presentation", "creative", "prioritization": a trade, a deliverable,
  //   a marketing noun ("ad creative"), a product manager's method ("backlog prioritization").
  // - "integrity", "resilience", "reliability": engineering asks ("data integrity", "system
  //   resilience") as often as traits.
  // "leadership" and "stakeholder management" are soft: postings ask for them in every field,
  // and "led a team of five" is evidence of leading, which stays the requirements judge's work.
  softSkills: [
    "communication",
    "interpersonal",
    "teamwork",
    "team player",
    "collaboration",
    "leadership",
    "ownership",
    "accountability",
    "initiative",
    "proactive",
    "problem solving",
    "critical thinking",
    "decision making",
    "attention to detail",
    "detail oriented",
    "self motivated",
    "growth mindset",
    "time management",
    "multitasking",
    "organizational",
    "organisational",
    "stakeholder management",
    "conflict resolution",
    "public speaking",
    "adaptability",
    "flexibility",
    "creativity",
    "curiosity",
    "empathy",
    "compassion",
    "emotional intelligence",
    "work ethic",
  ],
  implies: {
    terraform: ["infrastructure as code"],
    kubernetes: ["containers"],
    docker: ["containers"],
    postgresql: ["relational database", "sql"],
    mysql: ["relational database", "sql"],
    react: ["javascript"],
    typescript: ["javascript"],
    // A role is experience in its field: a teacher's years are years in education.
    teacher: ["education"],
    nurse: ["healthcare"],
    // A software engineer's work is software development, though the role never says
    // "developed"; an engineer of another kind (sales, civil) is not.
    "software engineer": ["software", "engineer", "development"],
  },
  phrases: [
    "infrastructure as code",
    "relational database",
    "machine learning",
    "continuous integration",
    "continuous delivery",
    "distributed systems",
    "event streaming",
    "unit testing",
    "code review",
    "ci/cd",
    // A slash joins two skills ("HTML/CSS" asks for both) except in a name written with one.
    "tcp/ip",
    "pl/sql",
    "a/b",
    "i/o",
    "ts/sci",
    "software engineer",
    // Kept whole: "business" is a stopword, and "development" alone is a software engineer's.
    "business development",
    "documentation",
    "containers",
    "sql",
  ],
  buzzwords: [
    "team player",
    "hard worker",
    "hardworking",
    "self-starter",
    "results-driven",
    "go-getter",
    "think outside the box",
    "synergy",
    "detail oriented",
    "detail-oriented",
  ],
};
